SGBromatologia/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import *
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('administracion.urls')),
    url(r'^admin/', include(admin.site.urls)),
    ]

administracion/urls.py
from django.conf.urls import url, include

from .views import AdminIndex

urlpatterns = [

	url(r'^$', AdminIndex.as_view(), name='admin-index'),
	url(r'^inspections/', include('inspections.urls', namespace='inspections')),
	url(r'^comercios/', include('administrativos.urls', namespace='administrativos')),
	url(r'^solicitudes/', include('solicitudes.urls', namespace='solicitudes')),
	#url(r'^inspections/', include('inspections.urls', namespace='inspections')),
	#url(r'^inspections/', include('inspections.urls', namespace='inspections')),
	
]

administrativos/urls.py
from django.conf.urls import url
from . import views

#esto es una lista
urlpatterns = [
	
	url(
		r'^$',
		views.ComercioList.as_view(),
		name='comercios-list'

	),

	url(
		r'^detalle/(?P<pk>\d+)/$',
		views.ComercioDetail.as_view(),
		name='comercios-detail'

	),

	url(
		r'^alta/$',
		views.ComercioCreate.as_view(),
		name='comercios-create'

	),

	url(
		r'^modificar/(?P<pk>\d+)/$',
		views.ComercioUpdate.as_view(),
		name = 'comercios-update'
	),

	url(
		r'^eliminar/(?P<pk>\d+)/$',
		views.ComercioDelete.as_view(),
		name = 'comercios-delete'
	),
]

inspections/urls.py
from django.conf.urls import url
from inspections.views import InspeccionList

urlpatterns = [
	
	url(
		r'^listar',
		InspeccionList.as_view(),
		name='inspecciones-list'

	),

]

administrativos/models.py
from django.db import models

class Rubros(models.Model):
	cod_rubro = models.IntegerField('Codigo del Rubro')
	nomb_rubro = models.CharField('Nombre del Rubro', max_length=150)

	def __str__(self):
		return self.nomb_rubro

class Comercios(models.Model):

	ALTA = 'SI'
	BAJA = 'NO'

	ACTIVO =(
		(ALTA,'Si'),
		(BAJA,'No')
		)

	nomb_comercio = models.CharField('Nombre Comercio', max_length=150)
	propietario = models.CharField('Nombre Propietario', max_length=150)
	dni = models.IntegerField('D.N.I')
	domicilio = models.CharField('Domicilio Local', max_length=150)
	numeracion = models.IntegerField('Numeracion')
	fecha_soli = models.DateField('Fecha de Solicitud')
	Activo = models.CharField('Activo', max_length=2, choices=ACTIVO)
	numero_expte = models.CharField('Numero de Expediente', max_length=150)
	rubro = models.ManyToManyField(Rubros, blank=True)

	def __str__(self):
		return '{} {}'.format(self.nomb_comercio,self.propietario)

comercios/models.py
from django.db import models

# Create your models here.

administrativos/forms.py
from django import forms
from django.forms import inlineformset_factory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Button, Div, Fieldset
from crispy_forms.bootstrap import FormActions, PrependedText

from administrativos.models import Comercios,Rubros



class AdministrativoForm(forms.ModelForm):

	class Meta:
		model = Comercios

		fields = (
			'nomb_comercio',
			'propietario',
			'dni',
			'domicilio',
			'numeracion',
			'fecha_soli',
			'Activo',
			'numero_expte',
			'rubro',
		)
	def __init__(self, *args, **kwargs):
		super(AdministrativoForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_tag = False

		propietario__nomb_comercio = Div(
			Div('propietario', css_class='col-md-6'),
			Div('nomb_comercio', css_class='col-md-6'),
			css_class='row'
		)

		dni__domicilio__numeracion = Div(
			Div('dni',css_class='col-md-4'),
			Div('domicilio',css_class='col-md-4'),
			Div('numeracion',css_class='col-md-4'),
			css_class='row'
		)

		fecha_soli__Activo = Div(
			Div('fecha_soli',css_class='col-md-6'),
	
			
			Div('Activo',css_class='col-md-6'),
			css_class='row'
		)

		numero_expte__rubro = Div(
			Div('numero_expte', css_class='col-md-6'),
			Div('rubro', css_class='col-md-6'),
			css_class='row'
		)

		self.helper.layout = Layout(
			propietario__nomb_comercio,
			dni__domicilio__numeracion,
			fecha_soli__Activo,
			numero_expte__rubro,

		)
		self.helper.layout.append(
			FormActions(
				Button('cancel', 'Cancelar', css_class='btn-danger', onclick="window.history.back()"),
				Submit('save','Guardar'),
			)

		)

administrativos/views.py
from django.shortcuts import render
from django_tables2 import SingleTableView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView
# Create your views here.


from .models import Comercios,Rubros
from .tables import ComerciosTable 
from .forms import AdministrativoForm


class ComercioList(SingleTableView):
	model = Comercios
	template_name = 'administrativos/Comercios_list.html'
	table_class = ComerciosTable

	# def get_queryset(self):
	# 	query = super(ComercioList,self).get_queryset
	# 	return query.filter(Activo=True)

class ComercioCreate(CreateView):
	model = Comercios
	template_name = 'administrativos/Comercios_form.html'
	form_class = AdministrativoForm
	success_url = reverse_lazy('administrativos:comercios-list')

class ComercioDetail(DetailView):
	model = Comercios
	template_name = 'administrativos/Comercios_detail.html'
	form_class = AdministrativoForm


class ComercioUpdate(UpdateView):
	model = Comercios
	template_name = 'administrativos/Comercios_form.html'
	form_class = AdministrativoForm
	success_url = reverse_lazy('administrativos:comercios-list')


class ComercioDelete(DeleteView):
	model = Comercios
	template_name = 'administrativos/Comercios_delete.html'
	success_url = reverse_lazy('administrativos:comercios-list')





	# def get_context_data(self, *args, **kwargs):
	# 	context = super(ComercioDetail, self).get_context_data(*args, **kwargs)
	# 	context['objetos'] = Rubros.objects.all()
	# 	return context
	
	

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(ComercioDetail, self).get_context_data(*args, **kwargs)
	# 	context['objeto2'] = Rubros.objects.get(comercios=self.object)
	# 	return context

comercios/views.py
from django.shortcuts import render

# Create your views here.

administrativos/templates/administrativos/Comercios_delete.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h2>¿Esta seguro de Eliminar el Comercio  {{object.nomb_comercio}} de {{object.propietario}}?</h2>
	<br>
	
	<button class="btn btn-danger" type="submit">Eliminar</button>

	<a class="btn btn-default" href="{% url 'administrativos:comercios-list' %}">Cancelar</a>
	
</form>

{% endblock %}

administrativos/templates/administrativos/Comercios_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load static %}

{% block head %}
  <!-- bostrap/estilos -->
  <link rel="stylesheet" href="{% static 'adminlte/bootstrap/css/bootstrap2.css' %}">
  <link rel="stylesheet" href="{% static 'adminlte/bootstrap/css/style2.css' %}">
{% endblock %}

{% block section-title %}
  <h3>Comercio</h3>
{% endblock %}



{% block content %}
<div class="white-wrapper">
        <div class="container">
            <div class="general_row">
                <div class="general-title text-center">
                    
                  
                </div>
                <br>
                <div class="row">
                    <div class="clearfix">
                        <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                            <div class="media-element clearfix">
                            <font color="black"><h3><span>{{ object.id }}- Propietario y N° Dni : {{ object.propietario }} , {{ object.dni }}</span></h3></font>
                                
                            </div><!-- end slider -->
                        </div><!-- end col-lg-6 -->

                        <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">
                            <div class="big_team_widget">
                                
                             <div class="doctor-details">
                                     
                                    <ul>
                                        <li><span> Nombre Comercio: </span> - {{ object.nomb_comercio }} </li>
                                        <li><span> Domicilio: </span> - {{ object.domicilio }}</li> 
                                        <li><span>Numeracion: </span> - {{ object.numeracion }}</li>
                                        <li><span>Fecha Solicitud: </span> - {{ object.fecha_soli }} </li>
                                        <li><span>Numero de Expediente: </span> - {{ object.numero_expte }} </li>
                                        <li><span>Rubros: </span>
                                        {% for rubro in comercios.rubro.all %}
                                                 <li>{{ rubro.nomb_rubro }}</li>
                                        {% endfor %}
                                        </li>
                                        
                                        <li><span>Comercio Activo: </span> - {{ object.Activo }}</li>

                                    </ul>
                                </div>
                                
                                
                                     <!-- <h2>Rubros</h2>
                                        <ul>
                                            {% for rubro in comercios.rubro.all %}
                                                 <li>{{ rubro.nomb_rubro }}</li>
                                            {% endfor %}
                                         </ul> -->
                                
                                    
                              </p>
                                <br>
                                <br>
                                <br>

                                <div class="social-icons">
                                    <span class="facebook"><a data-toggle="tooltip" data-placement="bottom" title="Facebook" href="#"><i class="fa fa-facebook"></i></a></span>
                                    <span class="google-plus"><a data-toggle="tooltip" data-placement="bottom" title="Google Plus" href="#"><i class="fa fa-google-plus"></i></a></span>
                                    <span class="twitter"><a data-toggle="tooltip" data-placement="bottom" title="Twitter" href="#"><i class="fa fa-twitter"></i></a></span>
                                    <span class="linkedin"><a data-toggle="tooltip" data-placement="bottom" title="Linkedin" href="#"><i class="fa fa-linkedin"></i></a></span>
                                </div><!-- end social icons -->
                            </div><!-- end big_team_widget -->
                        </div><!-- end col-lg-6 -->
                    </div><!-- end fullwidth -->
                </div><!-- end row -->
                
                
            </div><!-- end general_row -->
        </div><!-- end container -->
    </div><!-- end white-wrapper -->

    <!-- <div class="dmtop" style="bottom: 25px; background-color:#23b8bf ">Scroll to Top</div> -->
{% endblock %}

administrativos/templates/administrativos/Comercios_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block section-title %}
  <h1>Nuevo Comercio</h1>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'administrativos:comercios-list' %}"><i class="fa fa-group"></i> Comercios</a></li>
  <li class="active">Nuevo</li>
{% endblock %}


{% block content %}
  <div class="row">
    <div class="col-md-8">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Datos del Comercio</h3>
        </div>
        <br>
        <!-- /.box-header -->
      <form action="." method="post" enctype="multipart/form-data">
        <div class="box-body">
        {% csrf_token %}
        {% crispy form %}
        <!-- {{ especialidad_formset.management_form }}
        {{ especialidad_formset.non_form_errors }}
        {% for esp_form in especialidad_formset %}
          {% crispy esp_form esp_form.helper %}
          {% for hidden_field in esp_form.hidden_fields %}
            {{ hidden_field }}
          {% endfor %}
        {% endfor %} -->
        </div>
        <br>
               <!-- /.box-footer -->
      </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    $(function () {
      //Initialize Select2 Elements
      $(".select2").select2();
      //Date picker
      // $.datepicker.setDefaults( $.datepicker.regional[ "es" ] );
      $('#id_fecha_soli').datepicker({
        autoclose: true,
        format: 'dd/mm/yyyy'
      });
    });
  </script>
{% endblock %}

administrativos/templates/administrativos/Comercios_list.html
{% extends 'base.html' %}


{% load staticfiles %}
{% load render_table from django_tables2 %}

{% block head %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables/dataTables.bootstrap.css' %}">
{% endblock %}

{% block section-title %}
<h1>Comercios</h1>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'administrativos:comercios-list' %}"><i class="fa fa-group"></i> Comercios</a></li>
  <li class="active">Listado</li>
{% endblock %}

{% block content %}
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header">
              <a class="btn btn-app" href="{% url 'administrativos:comercios-create' %}">
                <i class="fa fa-user"></i> Nuevo
              </a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              {% render_table table %}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
{% endblock %}

{% block scripts %}
<!-- DataTables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#administrativos').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}

administrativos/templates/administrativos/list_controls.html
<div class="btn-group" role="group" style="display: flex !important;">
  <a href="{% url 'administrativos:comercios-detail' record.pk %}" class="btn btn-info btn-xs">Ver</a>
  <a href="{% url 'administrativos:comercios-update' record.pk %}" class="btn btn-warning btn-xs">Editar</a>
  <a href="{% url 'administrativos:comercios-delete' record.pk %}" class="btn btn-danger btn-xs">Eliminar</a>
  <!-- <a href="#" class="btn btn-success btn-xs">Activar</a> -->
</div>