SGBromatologia/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import *
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('administracion.urls')),
    url(r'^admin/', include(admin.site.urls)),
    ]

administracion/urls.py
from django.conf.urls import url, include

from .views import AdminIndex

urlpatterns = [

	url(r'^$', AdminIndex.as_view(), name='admin-index'),
	url(r'^inspections/', include('inspections.urls', namespace='inspections')),
	url(r'^comercios/', include('administrativos.urls', namespace='administrativos')),
	url(r'^solicitudes/', include('solicitudes.urls', namespace='solicitudes')),
	#url(r'^inspections/', include('inspections.urls', namespace='inspections')),
	#url(r'^inspections/', include('inspections.urls', namespace='inspections')),
	
]

inspections/urls.py
from django.conf.urls import url
from inspections.views import InspeccionList

urlpatterns = [
	
	url(
		r'^listar',
		InspeccionList.as_view(),
		name='inspecciones-list'

	),

]

solicitudes/urls.py
from django.conf.urls import url
from . import views

#esto es una lista
urlpatterns = [
	
	url(
		r'^$',
		views.SolicitudList.as_view(),
		name='solicitudes-list'

	 ),

	# url(
	# 	r'^detalle/(?P<pk>\d+)/$',
	# 	views.ComercioDetail.as_view(),
	# 	name='comercios-detail'

	#),

	url(
		r'^alta/$',
		views.SolicitudCreate.as_view(),
		name='solicitudes-create'

	),

	# url(
	# 	r'^modificar/(?P<pk>\d+)/$',
	# 	views.ComercioUpdate.as_view(),
	# 	name = 'comercios-update'
	# ),

	# url(
	# 	r'^eliminar/(?P<pk>\d+)/$',
	# 	views.ComercioDelete.as_view(),
	# 	name = 'comercios-delete'
	# ),
]

solicitudes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from administrativos.models import Comercios

class Inspectores(models.Model):
	nombre = models.CharField('Nombre', max_length=100)
	apellido = models.CharField('Apellido', max_length=100)
	dni = models.CharField('DNI', max_length=8)
	tel = models.IntegerField('Telefono')
	estado = models.BooleanField('Disponibilidad', default=True)

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellido)


class Solicitud(models.Model):
	solicitud_id = models.AutoField(primary_key=True)
	fecha_solicitud = models.DateField('Fecha de Solicitud')
	comercios = models.ForeignKey(Comercios, null=True, blank=True ,on_delete=models.CASCADE)
	inspector = models.ForeignKey(Inspectores, null=True, blank=True, on_delete=models.CASCADE)
	num_expte = models.PositiveIntegerField('Numero de Expediente' , null=True)


	def __str__(self):
		return '{} {} {}'.format(self.solicitud_id,self.fecha_solicitud,self.inspector)
		

solicitudes/forms.py
from django import forms
from django.forms import inlineformset_factory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Button, Div, Fieldset
from crispy_forms.bootstrap import FormActions, PrependedText

from solicitudes.models import Solicitud



class SolicitudForm(forms.ModelForm):

	class Meta:
		model = Solicitud

		fields = (
			'fecha_solicitud',
			'comercios',
			'inspector',
			'num_expte',
			
		)
	def __init__(self, *args, **kwargs):
		super(SolicitudForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_tag = False

		fecha_solicitud__num_expte = Div(
			Div('fecha_solicitud', css_class='col-md-6'),
			Div('num_expte', css_class='col-md-6'),
			css_class='row'
		)

		comercios__inspector = Div(
			Div('comercios',css_class='col-md-6'),
			Div('inspector',css_class='col-md-6'),
			css_class='row'
		)

		

		self.helper.layout = Layout(
			fecha_solicitud__num_expte,
			comercios__inspector,

		)
		self.helper.layout.append(
			FormActions(
				Button('cancel', 'Cancelar', css_class='btn-danger', onclick="window.history.back()"),
				Submit('save','Guardar'),
			)

		)

solicitudes/views.py
from django.shortcuts import render
from django_tables2 import SingleTableView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView
# Create your views here.


from .models import Solicitud
from .tables import SolicitudesTable 
from .forms import SolicitudForm


class SolicitudList(SingleTableView):
	model = Solicitud
	template_name = 'solicitudes/Solicitudes_list.html'
	table_class = SolicitudesTable

# class CreateSolicitud(CreateView):
# 	model

class SolicitudCreate(CreateView):
	model = Solicitud
	template_name = 'solicitudes/Solicitud_form.html'
	form_class = SolicitudForm
	success_url = reverse_lazy('solicitudes:solicitudes-list')

solicitudes/templates/solicitudes/Solicitud_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block section-title %}
  <h1>Nueva Solicitud</h1>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'solicitudes:solicitudes-list' %}"><i class="fa fa-group"></i> Solicitudes</a></li>
  <li class="active">Nuevo</li>
{% endblock %}


{% block content %}
  <div class="row">
    <div class="col-md-8">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Datos del Solicitante</h3>
        </div>
        <br>
        <!-- /.box-header -->
      <form action="." method="post" enctype="multipart/form-data">
        <div class="box-body">
        {% csrf_token %}
        {% crispy form %}
        <!-- {{ especialidad_formset.management_form }}
        {{ especialidad_formset.non_form_errors }}
        {% for esp_form in especialidad_formset %}
          {% crispy esp_form esp_form.helper %}
          {% for hidden_field in esp_form.hidden_fields %}
            {{ hidden_field }}
          {% endfor %}
        {% endfor %} -->
        </div>
        <br>
               <!-- /.box-footer -->
      </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    $(function () {
      //Initialize Select2 Elements
      $(".select2").select2();
      //Date picker
      // $.datepicker.setDefaults( $.datepicker.regional[ "es" ] );
      $('#id_fecha_solicitud').datepicker({
        autoclose: true,
        format: 'dd/mm/yyyy'
      });
    });
  </script>
{% endblock %}

solicitudes/templates/solicitudes/Solicitudes_list.html
{% extends 'base.html' %}


{% load staticfiles %}
{% load render_table from django_tables2 %}

{% block head %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/datatables/dataTables.bootstrap.css' %}">
{% endblock %}

{% block section-title %}
<h1>Solicitudes</h1>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'solicitudes:solicitudes-list' %}"><i class="fa fa-group"></i>Solicitudes</a></li>
  <li class="active">Solicitudes</li>
{% endblock %}

{% block content %}
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header">
              <a class="btn btn-app" href="{% url 'solicitudes:solicitudes-create' %}">
                <i class="fa fa-user"></i> Nuevo
              </a>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              {% render_table table %}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
{% endblock %}

{% block scripts %}
<!-- DataTables -->
<script src="{% static 'adminlte/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<!-- page script -->
<script>
  $(function () {
    $('#solicitudes').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}

solicitudes/templates/solicitudes/list_controls.html
<div class="btn-group" role="group" style="display: flex !important;">
  <a href="{#}" class="btn btn-info btn-xs">Ver</a>
  <a href="{#}" class="btn btn-warning btn-xs">Editar</a>
  <a href="{#}" class="btn btn-danger btn-xs">Eliminar</a>
  <!-- <a href="#" class="btn btn-success btn-xs">Activar</a> -->
</div>